# Copyright (c) 2018, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "is-pattern-1.resource.prefix" . }}-identity-server-conf
  namespace : {{ .Release.Namespace }}
  {{ if .Values.wso2.deployment.wso2is.config }}

data:
  {{- range $index, $content := .Values.wso2.deployment.wso2is.config }}
  {{ $index }}: |-
  {{ tpl $content $ | indent 4 }}
  {{- end }}

  {{ else }}
data:
  deployment.toml: |-
    # Deployment config for Identity Server deployment
    [server]
    hostname = "{{ .Values.wso2.deployment.wso2is.ingress.identity.hostname }}"
    node_ip = "$env{NODE_IP}"
    base_path = "https://$ref{server.hostname}"

    [super_admin]
    username = "admin"
    password = "admin"
    create_admin_account = true

    [user_store]
    type = "database_unique_id"

    [database.user]
    type = "postgre"
    url = "jdbc:postgresql://10.27.64.3:5432/wso2is?currentSchema=wso2is_shared_db"
    username = "vinloyalty"
    password = "1qazxsw@"
    driver = "org.postgresql.Driver"

    [database.user.pool_options]
    validationQuery = "SELECT 1"

    [transport.https.properties]
    proxyPort="443"

    [database.identity_db]
    type = "postgre"
    url = "jdbc:postgresql://10.27.64.3:5432/wso2is?currentSchema=wso2is_identity_db"
    username = "vinloyalty"
    password = "1qazxsw@"
    driver = "org.postgresql.Driver"

    [database.identity_db.pool_options]
    validationQuery = "SELECT 1"

    [database.shared_db]
    type = "postgre"
    url = "jdbc:postgresql://10.27.64.3:5432/wso2is?currentSchema=wso2is_shared_db"
    username = "vinloyalty"
    password = "1qazxsw@"
    driver = "org.postgresql.Driver"

    [truststore]
    file_name="client-truststore.jks"
    password="wso2carbon"
    type="JKS"

    [account_recovery.endpoint.auth]
    hash= "66cd9688a2ae068244ea01e70f0e230f5623b7fa4cdecb65070a09ec06452262"

    [identity.auth_framework.endpoint]
    app_password= "dashboard"

    [database.shared_db.pool_options]
    validationQuery = "SELECT 1"

    [database.bps_database]
    type = "postgre"
    url = "jdbc:postgresql://10.27.64.3:5432/wso2is?currentSchema=wso2is_bps_db"
    username = "vinloyalty"
    password = "1qazxsw@"
    driver = "org.postgresql.Driver"

    [database.bps_database.pool_options]
    validationQuery = "SELECT 1"

    [[datasource]]
    id = "WSO2ConsentDS"
    type = "postgre"
    url = "jdbc:postgresql://10.27.64.3:5432/wso2is?currentSchema=wso2is_consent_db"
    username = "vinloyalty"
    password = "1qazxsw@"
    driver = "org.postgresql.Driver"
    pool_options.validationQuery="SELECT 1"
    pool_options.maxActive=50
    pool_options.maxWait = 60000 # wait in milliseconds
    pool_options.testOnBorrow = true
    pool_options.jmxEnabled = false
    [authentication.consent]
    data_source="jdbc/WSO2ConsentDS"

    [keystore.primary]
    name = "wso2carbon.jks"
    password = "wso2carbon"

    [clustering]
    membership_scheme = "kubernetes"
    domain = "wso2.carbon.domain"
    properties.membershipSchemeClassName = "org.wso2.carbon.membership.scheme.kubernetes.KubernetesMembershipScheme"
    properties.KUBERNETES_NAMESPACE = "{{ .Release.Namespace }}"
    properties.KUBERNETES_SERVICES = "{{ template "is-pattern-1.resource.prefix" . }}-identity-service"
    properties.KUBERNETES_MASTER_SKIP_SSL_VERIFICATION = "true"
    properties.USE_DNS = "false"

    [[event_listener]]
    id = "token_revocation"
    type = "org.wso2.carbon.identity.core.handler.AbstractIdentityHandler"
    name = "org.wso2.is.notification.ApimOauthEventInterceptor"
    order = 1

    [[resource.access_control]]
    context = "(.)/keymanager-operations/user-info/claims(.)"
    secure = true
    http_method = "GET"
    permissions = "/permission/admin/manage/identity/usermgt/list"
    scopes = "internal_user_mgt_list"

    [[resource.access_control]]
    context = "(.*)/keymanager-operations/user-info/claims/generate"
    secure = true
    http_method = "POST"
    permissions = "/permission/admin/manage/identity/usermgt/list"
    scopes = "internal_user_mgt_list"

    [[resource.access_control]]
    context = "(.*)/keymanager-operations/dcr/register"
    secure = true
    http_method = "POST"
    permissions = "/permission/admin/manage/identity/applicationmgt/create"
    scopes = "internal_application_mgt_create"

    [[resource.access_control]]
    context = "(.*)/keymanager-operations/dcr/register(.*)"
    secure = true
    http_method = "GET"
    permissions = "/permission/admin/manage/identity/applicationmgt/view"
    scopes = "internal_application_mgt_view"

    [[resource.access_control]]
    context = "(.*)/keymanager-operations/dcr/register(.*)"
    secure = true
    http_method = "DELETE"
    permissions = "/permission/admin/manage/identity/applicationmgt/delete"
    scopes = "internal_application_mgt_delete"

    [[resource.access_control]]
    context = "(.*)/keymanager-operations/dcr/register(.*)"
    secure = true
    http_method = "PUT"
    permissions = "/permission/admin/manage/identity/applicationmgt/update"
    scopes = "internal_application_mgt_update"

    [[resource.access_control]]
    context = "(.)/keymanager-operations/dcr/register(.)"
    secure = true
    http_method = "POST"
    permissions = "/permission/admin/manage/identity/applicationmgt/update"
    scopes = "internal_application_mgt_update"

    [[resource.access_control]]
    context = "/sample-auth(.*)"
    secure = false
    http_method = "all"

    [tenant_context.rewrite]
    custom_webapps = ["/keymanager-operations/"]

    [event_listener.properties]
    notification_endpoint = "https://localhost:9443/internal/data/v1/notify"
    username = "${admin.username}"
    password = "${admin.password}"
    'header.X-WSO2-KEY-MANAGER' = "WSO2IS"

    [cors]
    allow_generic_http_requests = true
    allow_any_origin = true
    allowed_origins = "*"

    [admin_service.wsdl]
    enable = true

    [oauth.token_renewal]
    renew_refresh_token = true

    [oauth.token_generation]
    access_token_type= "self_contained"

    [[oauth.custom_grant_type]]
    name="vinloyalty"
    grant_handler="org.wso2.identity.oauth2.grant.vinloyalty.VinloyaltyCustomGrant"
    grant_validator="org.wso2.identity.oauth2.grant.vinloyalty.VinloyaltyCustomGrantValidator"

    [oauth.custom_grant_type.properties]
    IdTokenAllowed=true
    
    {{ if .Values.wso2.monitoring.enabled }}
    [monitoring.jmx]
    rmi_server_start = true
    {{- end }}
  {{- end }}
